id: PA9609558
initial_creation_type: ocr
source_metadata:
  volumes:
    dbd92d6b95b243dd87863ffb0c67834f:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: མཛད་པ་བཅུ་གཉིས་ཀྱི་ཚུལ་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
